# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - main
      - feature/**
      - hotfix/**

pr:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  dotnetVersion: "8.x"
  cacheKey: 'nuget | "$(Agent.OS)" | **/packages.lock.json'

stages:
  # - stage: Build
  #   jobs:
  #     - job: build
  #       displayName: "Build job"
  #       steps:
  #         - template: ./build/build.yml
  #           parameters:
  #             buildConfiguration: "Release"
  #             buildPlatform: "Any CPU"

  - stage: GithubRelease
    displayName: "Github Release"
    condition: |
      or(
        and(
            eq(variables['Build.Reason'], 'PullRequest'),
            eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/main')
        ),
        and(
            eq(variables['Build.SourceBranch'], 'refs/heads/main'),
            or(
                eq(variables['Build.Reason'], 'Manual'),
                eq(variables['Build.Reason'], 'IndividualCI'),
                eq(variables['Build.Reason'], 'BatchedCI')
            )
        )
      )
    jobs:
      - job: CreateRelase
        displayName: "Create Release Tag"
        steps:
          - checkout: self
          - script: |
              echo "##[section] Generating release version"
              RELEASE_TAG="v1.0.$(Build.BuildId)"
              echo "Generated Release Tag: $RELEASE_TAG"
              echo "##vso[task.setvariable variable=RELEASE_TAG]$RELEASE_TAG"

            displayName: "Generate Release Tag"
            name: setReleaseTag # Required for referencing in the next stage

          - task: GitHubRelease@1
            displayName: "Create GitHub Release"
            inputs:
              gitHubConnection: "github.com_sharthak1095"
              repositoryName: "Scaler-io/Blogsphere.IdentityService"
              action: "create"
              tagSource: "userSpecifiedTag"
              tag: "$(RELEASE_TAG)"
              title: "Release $(RELEASE_TAG)"
              changeLogCompareToRelease: "lastFullRelease"
              changeLogType: "commitBased"

  - stage: Docker
    displayName: "Docker build and push"
    dependsOn: GithubRelease
    condition: |
      or(
        and(
            eq(variables['Build.Reason'], 'PullRequest'),
            eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/main')
        ),
        and(
            eq(variables['Build.SourceBranch'], 'refs/heads/main'),
            or(
                eq(variables['Build.Reason'], 'Manual'),
                eq(variables['Build.Reason'], 'IndividualCI'),
                eq(variables['Build.Reason'], 'BatchedCI')
            )
        )
      )
    variables:
      RELEASE_TAG: $[ dependencies.GithubRelease.outputs['CreateRelease.setReleaseTag.RELEASE_TAG'] ]
    jobs:
      - job: DockerBuild
        displayName: "Build docker image"
        steps:
          - script: |
              echo $(RELEASE_TAG)
          - template: ./deploy/docker.yml
            parameters:
              imageName: "sharthak1995/blogsphere.identity.svc"
              tag: "$(RELEASE_TAG)"
