# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - main
      - feature/**
      - hotfix/**

pr:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  dotnetVersion: "8.x"
  cacheKey: 'nuget | "$(Agent.OS)" | **/packages.lock.json'

stages:
  - stage: Build
    jobs:
      - job: build
        displayName: "Build job"
        steps:
          - template: ./build/build.yml
            parameters:
              buildConfiguration: "Release"
              buildPlatform: "Any CPU"

  - stage: Docker
    displayName: "Docker build and push"
    condition: |
      or(
        and(
          eq(variables['Build.Reason'], 'PullRequest'),
          eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/main')
        ),
        and(
          eq(variables['Build.SourceBranch'], 'refs/heads/main'),
          eq(variables['Build.Reason'], 'Manual')
        )
      )
    jobs:
      - job: DockerBuild
        displayName: "Build docker image"
        steps:
          - template: ./deploy/docker.yml
            parameters:
              imageName: "sharthak1995/blogsphere.identity.svc"
              tag: "$(Build.BuildId)"
