# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - main
      - feature/**
      - hotfix/**

pr:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  dotnetVersion: "8.x"
  cacheKey: 'nuget | "$(Agent.OS)" | **/packages.lock.json'

stages:
  # Build and test dotnet app
  - stage: Build
    jobs:
      - job: build
        displayName: "Build job"
        steps:
          - template: ./build/build.yml
            parameters:
              buildConfiguration: "Release"
              buildPlatform: "Any CPU"

  # Create github release and tag
  - stage: GithubRelease
    displayName: "Github Release"
    condition: |
      and(
        succeeded(),
        or(
          and(
              eq(variables['Build.Reason'], 'PullRequest'),
              eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/main')
          ),
          and(
              eq(variables['Build.SourceBranch'], 'refs/heads/main'),
              or(
                  eq(variables['Build.Reason'], 'Manual'),
                  eq(variables['Build.Reason'], 'IndividualCI'),
                  eq(variables['Build.Reason'], 'BatchedCI')
              )
          )
        )
      )
    jobs:
      - job: CreateRelease
        displayName: "Create Release Tag"
        steps:
          template: ./deploy/github-release.yml

  # Docker build and push
  - stage: Docker
    displayName: "Docker build and push"
    dependsOn: GithubRelease
    condition: |
      and(
        succeeded(),
        or(
          and(
              eq(variables['Build.Reason'], 'PullRequest'),
              eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/main')
          ),
          and(
              eq(variables['Build.SourceBranch'], 'refs/heads/main'),
              or(
                  eq(variables['Build.Reason'], 'Manual'),
                  eq(variables['Build.Reason'], 'IndividualCI'),
                  eq(variables['Build.Reason'], 'BatchedCI')
              )
          )
        )
      )
    variables:
      RELEASE_TAG: $[ stageDependencies.GithubRelease.CreateRelease.outputs['setReleaseTag.RELEASE_TAG'] ]
    jobs:
      - job: DockerBuild
        displayName: "Build docker image"
        steps:
          - script: |
              echo $(RELEASE_TAG)
          - template: ./deploy/docker.yml
            parameters:
              imageName: "sharthak1995/blogsphere.identity.svc"
              tag: "$(RELEASE_TAG)"
