# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - main
      - feature/**
      - hotfix/**

pr:
  branches:
    include:
      - main

pool:
  vmImage: "windows-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  dotnetVersion: "8.x"
  cacheKey: 'nuget | "$(Agent.OS)" | **/packages.lock.json'

steps:
  - task: UseDotNet@2
    displayName: "Install .NET SDK"
    inputs:
      packageType: "sdk"
      version: $(dotnetVersion)

  - task: DotNetCoreCLI@2
    displayName: "Restore dependencies"
    inputs:
      command: "restore"
      projects: "**/IdentityService.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Build solution"
    inputs:
      command: "build"
      projects: "**/IdentityService.csproj"
      arguments: "--configuration $(buildConfiguration) --platform $(buildPlatform)"

  - task: DotNetCoreCLI@2
    displayName: "Publish API"
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "**/*.csproj"
      arguments: "--configuration $(buildConfiguration) --platform $(buildPlatform) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish build artifacts"
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "IdentiyServer"
