steps:
  - checkout: self
  - script: |
      echo "##[section] Generating release version"
      RELEASE_TAG="v1.0.$(Build.BuildId)"
      echo "Generated Release Tag: $RELEASE_TAG"
      echo "##vso[task.setvariable variable=RELEASE_TAG;isOutput=true]v1.0.$(Build.BuildId)"
    displayName: "Generate Release Tag"
    name: setReleaseTag # Required for referencing in the next stage

  - task: GitHubRelease@1
    displayName: "Create GitHub Release"
    inputs:
      gitHubConnection: "github.com_sharthak1095"
      repositoryName: "Scaler-io/Blogsphere.IdentityService"
      action: "create"
      tagSource: "userSpecifiedTag"
      tag: "v1.0.$(Build.BuildId)"
      title: "Release v1.0.$(Build.BuildId)"
      changeLogCompareToRelease: "lastFullRelease"
      changeLogType: "commitBased"
